interface=wlan0_ap
driver=nl80211
ssid=epaper-display
country_code=US

hw_mode=g
channel=6

wmm_enabled=0

auth_algs=1
ignore_broadcast_ssid=0

wpa=2
wpa_passphrase=colebottest
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP